<a href="https://colab.research.google.com/github/solverharsh/Python_NumPy/blob/main/NumPy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What is numpy?**
* NumPy is the fundamental package for **scientific** computing in Python.
* It is a Python **library** that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
* At the core of the NumPy package, is the **ndarray** object. This encapsulates n-dimensional arrays of homogeneous data types.







**Numpy Arrays Vs Python Sequences :**
* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.



**1D array :**
* A 1D array is a simple list of elements in a single row or column.

In [2]:
# np.array
import numpy as np

arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)

[1 2 3 4]


**2D array (matrix) :**
* A 2D array has two dimensions: rows and columns, like a table or matrix.

In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**3D Array :**
* A 3D array extends the idea of 2D arrays by adding a third dimension, like a cube or a stack of matrices. In a 3D array, each element is accessed with three indices: [depth][row][column].

* Think of it as a stack of 2D arrays. For example, imagine a box containing three 2D arrays (like multiple pages in a book):

In [10]:
# 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(arr_3d)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [12]:
a_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(a_3d)
# Here, the array consists of 3 layers (depth), and each layer has 2 rows and 3 columns.

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


**Conclusion :**
* A 3D array is a multi-dimensional structure where each element is indexed by three values: [depth][row][column].

* It's like a stack of 2D matrices, and you can access and manipulate individual elements, rows, or layers.

* You can apply operations to 3D arrays just like any other NumPy array, and it’s very useful for working with things like images, volumes, or scientific data that require three dimensions.

**1. What is dtype?**
* dtype (short for "data type") in NumPy refers to the type of the elements in the array.

* It determines the format of the data stored in the array and how much memory each element occupies.

* Every NumPy array has an associated dtype object, which defines the type and properties of the array's elements.

**2. Why is dtype important?**
* The dtype ensures efficient use of memory by specifying the size of the data elements.
* It also allows NumPy to perform optimized operations based on the data type (e.g., using hardware-specific instructions).
* It helps you perform type-specific operations (e.g., performing mathematical operations on floating-point numbers, integer numbers, etc.).

In [4]:
dt = np.array(['1', '2'], dtype='timedelta64[D]')
print(dt)

[1 2]


In [5]:
dt = np.array(['2021-01-01', '2022-02-02'], dtype='datetime64[D]')
print(dt)

['2021-01-01' '2022-02-02']


In [6]:
arr = np.array([1,2,3],dtype = np.int32)
print(arr.dtype)

int32


In [7]:
arr = np.array([1,2,3],dtype = np.float64)
print(arr.dtype)

float64


**Type Casting (Changing dtype)**  
* You can change the dtype of an existing NumPy array using the astype() method

In [9]:
arr = np.array([1,2,3,4] , dtype = np.float64)
print(arr.dtype)

arr1 = arr.astype(np.int32)
print(arr1.dtype)

float64
int32
